"""Core functionality for the context_writer package"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_core.ipynb.

# %% auto 0
__all__ = ['get_secret_word', 'AppConfig']

# %% ../nbs/01_core.ipynb 3
from typing import Dict, Any

# Testing imports (not exported)
from fastcore.test import test_eq, test_ne

# %% ../nbs/01_core.ipynb 5
def get_secret_word() -> str:
    """Return the secret word for the application.
    
    This is a test function to verify nbdev integration is working.
    """
    return "🚀 NBDEV-POWERED"

# %% ../nbs/01_core.ipynb 9
class AppConfig:
    """Configuration for the context_writer application."""
    
    def __init__(self, app_name: str = "Context Writer"):
        self.app_name = app_name
        self.version = "0.0.1"
        self.secret = get_secret_word()
    
    def get_title(self) -> str:
        """Get the full application title including the secret word."""
        return f"{self.app_name} - {self.secret}"
    
    def get_info(self) -> Dict[str, Any]:
        """Get application information as a dictionary."""
        return {
            "name": self.app_name,
            "version": self.version,
            "secret": self.secret,
            "powered_by": "nbdev + FastHTML"
        }
